# Generated by Django 3.0.11 on 2021-01-11 21:18

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_modulelearningspacerelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='learning_outcomes',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Learning Outcomes (displays on Overview tab)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='overview_copy',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Details Tab Copy'),
        ),
    ]
