# Generated by Django 3.0.11 on 2020-12-16 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_learningspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='program_description',
        ),
    ]
