# Generated by Django 3.0.11 on 2021-01-11 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_remove_program_program_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningspace',
            options={'managed': True, 'verbose_name': 'Learning Space', 'verbose_name_plural': 'Learning Spaces'},
        ),
    ]
